// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtdem6AYIfMxyJHyJl11UCwkXumSdiiP0',
    appId: '1:125198357397:web:fca90813f8aea3db9b5c9c',
    messagingSenderId: '125198357397',
    projectId: 'music-app-90fdd',
    authDomain: 'music-app-90fdd.firebaseapp.com',
    storageBucket: 'music-app-90fdd.appspot.com',
    measurementId: 'G-998Z2VGKVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdkud8UXu2ZZpwaQ9IMig9EjG1eLzvhoA',
    appId: '1:125198357397:android:45a2eb6b74304a9d9b5c9c',
    messagingSenderId: '125198357397',
    projectId: 'music-app-90fdd',
    storageBucket: 'music-app-90fdd.appspot.com',
  );
}
